export const PERMISSIONS = {
  SITE_READ: "SITE_READ",
  SITE_UPDATE: "SITE_UPDATE",
  SITE_DELETE: "SITE_DELETE",
  PAGE_CREATE: "PAGE_CREATE",
  PAGE_UPDATE: "PAGE_UPDATE",
  PAGE_DELETE: "PAGE_DELETE",
};