import { PERMISSIONS } from "./permissions";
import { Role } from "../../modules/auth/role";

export const ROLE_PERMISSIONS: Record<Role, readonly string[]> = {
  OWNER: [
    PERMISSIONS.SITE_READ,
    PERMISSIONS.SITE_UPDATE,
    PERMISSIONS.SITE_DELETE,
    PERMISSIONS.PAGE_CREATE,
    PERMISSIONS.PAGE_UPDATE,
    PERMISSIONS.PAGE_DELETE,
  ],
  ADMIN: [
    PERMISSIONS.SITE_READ,
    PERMISSIONS.SITE_UPDATE,
    PERMISSIONS.PAGE_CREATE,
    PERMISSIONS.PAGE_UPDATE,
  ],
  EDITOR: [
    PERMISSIONS.PAGE_CREATE,
    PERMISSIONS.PAGE_UPDATE,
  ],
  VIEWER: [
    PERMISSIONS.SITE_READ,
  ],
};